// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVxloOhJmkSK8RsapAmo4aGMXwk4bB1l0',
    appId: '1:360144847156:web:d6f4a9dc2968b6a61d2561',
    messagingSenderId: '360144847156',
    projectId: 'neuro-ninjaa',
    authDomain: 'neuro-ninjaa.firebaseapp.com',
    storageBucket: 'neuro-ninjaa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTkZ-ULQRb2tkZLtmbAsmP31RWhXw6K4Q',
    appId: '1:360144847156:android:74e1867c79ba72c71d2561',
    messagingSenderId: '360144847156',
    projectId: 'neuro-ninjaa',
    storageBucket: 'neuro-ninjaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrjAy4CNO__PcQoGYAIPiePgFtvqlpwGA',
    appId: '1:360144847156:ios:f0b1f14597cd51541d2561',
    messagingSenderId: '360144847156',
    projectId: 'neuro-ninjaa',
    storageBucket: 'neuro-ninjaa.firebasestorage.app',
    iosBundleId: 'com.example.neuroNinja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrjAy4CNO__PcQoGYAIPiePgFtvqlpwGA',
    appId: '1:360144847156:ios:f0b1f14597cd51541d2561',
    messagingSenderId: '360144847156',
    projectId: 'neuro-ninjaa',
    storageBucket: 'neuro-ninjaa.firebasestorage.app',
    iosBundleId: 'com.example.neuroNinja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVxloOhJmkSK8RsapAmo4aGMXwk4bB1l0',
    appId: '1:360144847156:web:73ba40398cd667d81d2561',
    messagingSenderId: '360144847156',
    projectId: 'neuro-ninjaa',
    authDomain: 'neuro-ninjaa.firebaseapp.com',
    storageBucket: 'neuro-ninjaa.firebasestorage.app',
  );
}
